# Generated by Django 3.0.3 on 2020-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200310_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
