# Generated by Django 3.0.3 on 2020-03-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productorders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
