# Generated by Django 3.0.3 on 2020-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productorders_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
