# Generated by Django 3.0.2 on 2020-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
