# Generated by Django 3.0.3 on 2020-03-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200324_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='app.SubProduct'),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderProduct', to='app.SubProduct'),
        ),
    ]
