# Generated by Django 3.0.3 on 2020-03-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200324_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='slider/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductCategory')),
            ],
        ),
    ]
