# Generated by Django 3.0.2 on 2020-01-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
