# Generated by Django 3.0.2 on 2020-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200129_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
